# Uncomment the next line to define a global platform for your project
 platform :ios, ‘8.0’

target '百思不得骑马强化' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 百思不得骑马强化

  pod 'AFNetworking', '~> 3.0.0'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'SVProgressHUD'
  pod 'MJRefresh'

  target '百思不得骑马强化UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
